"""Tier-2 GOLDEN / characterization tests for the clock labs (Backlog.md #9).

The whole edifice emits numbers we make buy/build decisions on. Tier 1 tests the
*cores*; this pins the *labs' output* so any refactor that shifts a clock fails
loudly and you decide fix-vs-regression (exactly what would have caught Grand
Design's "39%→89%" fetch bug at the lab level, not just in deck_sim).

Two tiers, per Backlog #9:

  EXACT      — re-run each clock lab at its fixed module SEED + a small pinned
               trial count and assert its decap/table curves match
               tests/golden/clock_snapshot.json BIT-FOR-BIT. The labs are
               deterministic at (seed, trials), so this is a true snapshot test:
               any code change that moves a number reds out here.
  TOLERANCE  — assert the cheap snapshot's median is within ±1 turn of the
               committed production curves in analysis/pod_gauntlet_clocks.json
               (harvested @8k). Ties the test artifact to the numbers the
               Summaries actually cite, so the snapshot can't be regenerated
               from a broken state and quietly bless it.

NOT hermetic: the labs need the 168 MB Scryfall bulk (collection/oracle-cards.json),
so these are marked `golden` and SKIPPED when the bulk is absent — the fast
`tests` CI job and bulk-free machines skip them; the bulk-having job + local runs
exercise them. DRY: the lab invocation + row parsing are reused verbatim from
pod_gauntlet (CLOCKS table, parse_row) — the same machinery `--refresh` uses.

Regenerate the snapshot after an INTENDED change (review the diff before commit):
    python tests/test_clock_golden.py --update
"""
import functools
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
# conftest puts scripts/ on the path under pytest; do it here too so the
# `--update` entry point (run as __main__, no conftest) imports the same way.
_SCRIPTS = str(ROOT / "scripts")
if _SCRIPTS not in sys.path:
    sys.path.insert(0, _SCRIPTS)

import pod_gauntlet as pg  # noqa: E402

BULK = ROOT / "collection" / "oracle-cards.json"
SNAPSHOT = Path(__file__).resolve().parent / "golden" / "clock_snapshot.json"
PROD = ROOT / "analysis" / "pod_gauntlet_clocks.json"

# Small + deterministic. The labs use a fixed module SEED, so (seed, TRIALS) is
# reproducible; TRIALS only sets where the snapshot is pinned, not whether it is.
TRIALS = 800

# Bit-for-bit Monte-Carlo output is reproducible across OS and PYTHONHASHSEED
# (verified — the labs don't branch on set iteration order), but it is NOT
# guaranteed across CPython MINOR versions (random's stream could shift). So the
# EXACT tier only asserts against a snapshot generated by the same major.minor;
# on a mismatch it skips and the cross-version-robust TOLERANCE tier carries the
# gate. Pin the CI golden job to this interpreter to keep EXACT live there.
PYVER = f"{sys.version_info.major}.{sys.version_info.minor}"

# Every deck whose clock comes from a single-deck lab. croak_and_dagger has
# lab=None (multi-variant; its curve is baked, not harvested) — nothing to rerun.
LABS = {s: c for s, c in pg.CLOCKS.items() if c["lab"]}

pytestmark = [
    pytest.mark.golden,
    pytest.mark.skipif(not BULK.exists(),
                       reason="Scryfall bulk (collection/oracle-cards.json) absent"),
]


@functools.lru_cache(maxsize=None)
def run_lab(slug):
    """Subprocess the lab exactly as pod_gauntlet.refresh does, then parse its
    decap/table curves with pod_gauntlet.parse_row. Returns
    {'decap': [...], 'table': [...] | None}. Cached so EXACT and TOLERANCE share
    one run per deck."""
    c = LABS[slug]
    script, mode = c["lab"]
    out = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / f"{script}.py"),
         "--mode", mode, "--trials", str(TRIALS)],
        capture_output=True, text=True, timeout=300, cwd=str(ROOT))
    assert out.returncode == 0, f"{script} failed:\n{out.stderr}"
    lines = out.stdout.splitlines()
    dsel, tsel = c["sel"]
    decap = pg.parse_row(lines, dsel, c["grid"])
    table = pg.parse_row(lines, tsel, c["grid"]) if tsel else None
    assert decap is not None, f"{slug}: couldn't parse decap row (sel {dsel!r})"
    return {"decap": decap, "table": table}


def curve_median(grid, curve):
    """Lowest grid turn whose cumulative P(kill) ≥ 50%, or grid[-1]+1 (= never
    crossed in horizon). Matches how the binned medians read off the curve."""
    for t, v in zip(grid, curve):
        if v >= 50:
            return t
    return grid[-1] + 1


@pytest.fixture(scope="session")
def snapshot():
    if not SNAPSHOT.exists():
        pytest.skip("no golden snapshot yet — run: python tests/test_clock_golden.py --update")
    return json.loads(SNAPSHOT.read_text(encoding="utf-8"))


def test_snapshot_covers_every_lab(snapshot):
    """The snapshot and the live lab roster must not drift apart silently — a
    new deck without a pinned snapshot (or a retired one still pinned) fails."""
    decks = snapshot["decks"]
    assert set(decks) == set(LABS), (
        f"snapshot drift: missing={set(LABS) - set(decks)}, "
        f"stale={set(decks) - set(LABS)} — rerun --update")


@pytest.mark.parametrize("slug", sorted(LABS))
def test_clock_matches_snapshot_exactly(slug, snapshot):
    """EXACT tier: the lab's curves are bit-for-bit what we pinned (same
    interpreter only — see PYVER note)."""
    snap_py = snapshot["_meta"]["python"]
    if snap_py != PYVER:
        pytest.skip(f"snapshot pinned under py{snap_py}, running py{PYVER} — "
                    f"bit-for-bit is interpreter-specific; tolerance tier still gates")
    decks = snapshot["decks"]
    if slug not in decks:
        pytest.skip(f"{slug} not in snapshot — run --update")
    assert run_lab(slug) == decks[slug], (
        f"{slug}: clock curves moved vs golden snapshot. If intended, "
        f"review then regenerate: python tests/test_clock_golden.py --update")


@pytest.mark.parametrize("slug", sorted(LABS))
def test_snapshot_median_tracks_production(slug, snapshot):
    """TOLERANCE tier: the snapshot median sits within ±1 turn of the committed
    @8k production curve, so the cheap snapshot can't drift from the Summaries.
    Cross-version robust — runs regardless of interpreter."""
    decks = snapshot["decks"]
    if slug not in decks:
        pytest.skip(f"{slug} not in snapshot — run --update")
    prod = json.loads(PROD.read_text(encoding="utf-8"))[slug]
    grid = prod["grid"]
    snap = decks[slug]
    for clock in ("decap", "table"):
        if snap.get(clock) is None or prod.get(clock) is None:
            continue
        sm = curve_median(grid, snap[clock])
        pm = curve_median(grid, prod[clock])
        assert abs(sm - pm) <= 1, (
            f"{slug} {clock}: snapshot median T{sm} drifted >1 turn from "
            f"production T{pm} — the lab and the committed clock disagree")


def _update():
    """Regenerate the golden snapshot from the current lab code."""
    if not BULK.exists():
        sys.exit("Scryfall bulk absent — can't run the labs to snapshot them.")
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    decks = {}
    for slug in sorted(LABS):
        decks[slug] = run_lab(slug)
        print(f"  {slug:24} decap={decks[slug]['decap']} table={decks[slug]['table']}")
    out = {"_meta": {"python": PYVER, "trials": TRIALS,
                     "note": "EXACT tier asserts vs this only under py" + PYVER +
                             "; regenerate with: python tests/test_clock_golden.py --update"},
           "decks": decks}
    SNAPSHOT.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {SNAPSHOT.relative_to(ROOT)} "
          f"({len(decks)} decks @ trials={TRIALS}, py{PYVER}, fixed lab seeds)")


if __name__ == "__main__":
    if "--update" in sys.argv:
        _update()
    else:
        sys.exit("usage: python tests/test_clock_golden.py --update")
