#!/usr/bin/env python3
"""deck_registry.py — the single source of truth for per-deck STATIC metadata.

Before this module the same per-deck facts were hand-typed across five files: the
identity tuple (slug / display name / decklist stem / commander) lived in
framework_bakeoff.DECKS, deck_sim.COMMANDERS+DISPLAY, pod_gauntlet.CLOCKS and
kill_tree.DECKS; the win line in framework_bakeoff.WIN_LINE; the mulligan judgment in
keep_spec.JUDGMENT/ALSO. Adding a deck meant editing all of them. Now each consumer
READS this registry, so a new deck is one row here (+ its bespoke `*_clock_lab.py`,
the one irreducible per-deck artifact — its turn-by-turn kill logic is code, not data).

What this module deliberately does NOT own:
  - the bespoke kill models / clock grids inside each `*_clock_lab.py` (irreducible;
    and the labs PIN a dated decklist for reproducibility, unlike the latest-resolving
    consumers here — so their paths stay local).
  - the harvested clock CURVES (grid/decap/table/med/never) in pod_gauntlet.CLOCKS and
    analysis/pod_gauntlet_clocks.json — those are lab OUTPUTS, regenerated by
    `pod_gauntlet.py --refresh`, not identity.
  - the oracle P(win) snapshots (RICHER_ORACLE / INTERACTION_ORACLE in
    framework_bakeoff) — also derived lab outputs.

Pure data + tiny helpers, NO heavy imports (no oracle load, no other local module), so
it sits below every consumer with no import cycles. Keyed by slug (underscore form);
each row's `stem` is the decklist filename prefix (== deck_sim's deck_key). Row ORDER is
load-bearing — it is the column order of the framework bake-off — so keep it stable.

Consumers and the accessor they use:
  framework_bakeoff  fb_decks()  win_lines()
  keep_spec          judgment()  also()
  deck_sim           active_commanders()  active_display()
  pod_gauntlet       lab pointer (DECKS[slug]["lab"])
  kill_tree          kill_trees()
  report.py          the whole row
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECK_DIR = ROOT / "decks"


# Row schema (per slug):
#   name        display name              stem        decklist filename prefix (= deck_key)
#   commander   command-zone card name    lab         (module, mode) of its clock lab, or None
#   cc          Conversion Check total    cc_axes     (core, kill, durability, interaction) or None
#   win_line    cheapest documented kill line (BDD mana-budget; pieces/override/fuzzy/line)
#   bottleneck  FINDING | MANA | BOARD    min/max_lands  mulligan keep band (closed)
#   hi_curve    tolerate a 4-land no-ramp keep            mixed   second-axis note (or None)
#   also        union-keep secondary axes (only present on genuinely two-line decks)
DECKS = {
    "genome_project": {
        "name": "The Genome Project", "stem": "the-genome-project",
        "commander": "Kuja, Genome Sorcerer", "lab": ("gp_clock_lab", "clock"),
        "cc": 15, "cc_axes": (4, 4, 3, 4),
        "win_line": {"pieces": ["City on Fire"], "fuzzy": True,
                     "line": "Trance Kuja + City on Fire (x3 dmg) — 1-2 casts kill the table"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "radiation_sickness": {
        "name": "Radiation Sickness", "stem": "radiation-sickness",
        "commander": "Wise Mothman", "lab": ("rs_clock_lab", "clock"),
        "cc": 18, "cc_axes": (5, 5, 4, 4),
        "win_line": {"pieces": ["Mindcrank", "Bloodchief Ascension"], "needs_cmdr": False,
                     "line": "Mindcrank + Bloodchief Ascension infinite (commander-independent)"},
        # Re-tagged FINDING->BOARD 2026-06-16: the FINDING keep dug for the Mindcrank/Bloodchief
        # combo (a SIDE line) and slowed the real clock (counter-grown board) -9pp at front7. The
        # board IS the fast decap; BOARD keep (Mothman on curve + early play) matches it. Union
        # (combo OR board) via `also`.  (analysis/Plan_Aware_Mulligan_2026-06-16.md)
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "combo is a side line; fast clock = counter-board (was FINDING, -9pp front7)",
        "also": ["FINDING"],   # BOARD primary (counter-grown board) + Mindcrank/Bloodchief combo upside
    },
    "replication_crisis": {
        "name": "The Replication Crisis", "stem": "the-replication-crisis",
        "commander": "Satya, Aetherflux Genius", "lab": ("rc_speed_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Sword of Feast and Famine", "Aggravated Assault"],
                     "line": "Satya + Sword of F&F + Aggravated Assault -> infinite combats"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "commander-gated; trigger on ATTACK (haste) — protect to swing",
        "also": ["FINDING"],   # BOARD primary (Satya attack) + Sword/Aggravated combo upside
        # key_extra (2026-07-03 re-tune): Satya+Lightning Runner is the PRIMARY infinite since the
        # 2026-06-22 swap (12% T6 vs the pair's 1-3%) but WIN_LINE still names the Sword/AA pair —
        # without this the keep ignored the deck's best card and Imperial Recruiter bridged to nothing.
        "key_extra": ["Lightning Runner"],
    },
    "lorehold_spirits": {
        "name": "Lorehold Spirits", "stem": "lorehold-spirit",
        "commander": "Quintorius, History Chaser", "lab": ("lor_clock_lab", "clock"),
        "cc": 18, "cc_axes": (5, 5, 4, 4),
        "win_line": {"pieces": ["Reveillark", "Karmic Guide", "Goblin Bombardment"],
                     "line": "Reveillark + Karmic Guide + Goblin Bombardment loop (table)"},
        # Re-tagged FINDING->BOARD 2026-06-16: the 3-card Reveillark loop is a side line; the fast
        # decap is spirits/Quintorius value, a BOARD clock (-4pp front7 under the FINDING keep).
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "3-card loop is a side line; fast clock = spirits/Quintorius (was FINDING, -4pp front7)",
        "also": ["FINDING"],   # BOARD primary (spirits/Quintorius) + 3-card Reveillark loop upside
    },
    "earthbend_the_meta": {
        "name": "Earthbend the Meta", "stem": "earthbend-the-meta",
        "commander": "Toph, the First Metalbender", "lab": ("ebm_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Triumph of the Hordes"], "fuzzy": True,
                     "line": "Triumph of the Hordes one-card closer from an earthbent board"},
        # also BOARD (2026-07-03 re-tune): the ramp-only MANA keep shipped on-curve Toph+payoff
        # hands with no ramp spell (lands alone cast the CMC-4 commander) — 24% of games started
        # "stuck". The union keeps those; ramp hands still keep via MANA.
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "lands-matter board also a payoff axis; BOARD union keeps on-curve no-ramp-spell hands",
        "also": ["BOARD"],
    },
    "exiles_return": {
        "name": "The Exile's Return", "stem": "the-exiles-return",
        "commander": "Fire Lord Zuko", "lab": ("er_speed_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Hellkite Charger"], "fuzzy": True,
                     "line": "Hellkite Charger + firebending extra-combats"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "zero_sum_game": {
        "name": "Zero-Sum Game", "stem": "zero-sum-game",
        "commander": "Witherbloom, the Balancer", "lab": ("wb_clock_lab", "clock"),
        "cc": 16, "cc_axes": (5, 5, 4, 2),   # audited 2026-06-27 (Interaction-floored); see Zero_Sum_Game_Summary.md
        "win_line": {"pieces": ["Exquisite Blood", "Sanguine Bond"], "needs_cmdr": False,
                     "line": "Exquisite Blood + Sanguine Bond loop + any life event (cmdr-indep.)"},
        "bottleneck": "FINDING", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
        # key_extra (2026-07-03 re-tune): the loop is 2 blood-halves x 4 payoff-halves; keying
        # only the WIN_LINE pair made the keep SHIP a complete Conqueror+Bloodlord combo. WIN_LINE
        # stays the cheapest documented line (bake-off cost basis); these widen the KEEP only.
        "key_extra": ["Bloodthirsty Conqueror", "Vito, Thorn of the Dusk Rose",
                      "Enduring Tenacity", "Defiant Bloodlord"],
    },
    "curse_of_the_scarab": {
        "name": "Curse of the Scarab", "stem": "curse-of-the-scarab",
        "commander": "The Scarab God", "lab": ("cos_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Gray Merchant of Asphodel"], "fuzzy": True,
                     "line": "Gray Merchant burst drain off black devotion"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 5, "hi_curve": False, "mixed": None,
    },
    "bumbleflower": {
        "name": "Ms. Bumbleflower", "stem": "this-bunny-goes-to-market",
        "commander": "Ms. Bumbleflower", "lab": ("bmf_clock_lab", "clock"),
        "cc": 15, "cc_axes": (4, 3, 3, 5),
        "win_line": {"pieces": ["Jolrael, Mwonvuli Recluse"], "fuzzy": True,
                     "line": "Jolrael alpha strike (lands -> X/X, X = hand size)"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "eldrazi_stampede": {
        "name": "Eldrazi Stampede Chaos", "stem": "eldrazi-stampede-chaos",
        "commander": "Maelstrom Wanderer", "lab": ("esc_clock_lab", "clock"),
        "cc": 14, "cc_axes": (4, 4, 3, 3),
        "win_line": {"pieces": ["Craterhoof Behemoth"], "fuzzy": True,
                     "line": "Craterhoof alpha over an Eldrazi/ramp board"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 5, "hi_curve": True, "mixed": None,
    },
    "dark_lords_army": {
        "name": "The Dark Lord's Army", "stem": "the-dark-lords-army",
        "commander": "Sauron, the Dark Lord", "lab": ("dla_clock_lab", "pod"),
        "cc": 19, "cc_axes": (5, 4, 5, 5),
        "win_line": {"pieces": ["Gray Merchant of Asphodel"], "fuzzy": True,
                     "line": "Sheoldred/Underworld Dreams/Wound Reflection drain + Gary close"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 5, "hi_curve": False, "mixed": None,
    },
    # Diminishing Returns (Teysa Karlov) DISMANTLED 2026-07-08 — retired to physically
    # source Zero-Sum Game + Forced Liquidation; decklist archived. Moved to
    # EXTRA_COMMANDERS below (Loam/Peace precedent). Was: cc 17 (5/4/4/4), FINDING,
    # lab dr_clock_lab. Its KILL_TREES entry was removed (kill_tree renders active decks
    # only); dr_clock_lab.py is kept as a historical artifact (now points at the archived list).
    "lightning_war": {
        "name": "Lightning War", "stem": "lightning-war",
        "commander": "Fire Lord Azula", "lab": ("lw_clock_lab", "bestline"),
        "cc": 19, "cc_axes": (5, 5, 4, 5),
        "win_line": {"pieces": ["Banefire"], "override": 14, "fuzzy": True,
                     "line": "X-burn finisher (Banefire/Crackle); ~14 mana from-40 lethal"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "flips at Azula: deploy CMC4 cmdr -> cheap-spell copy engine; tutors find the T9 combo",
        "also": ["FINDING"],   # 2026-07-03 re-tune: the T9 Reiterate+Seething combo is the fast
        # line and the deck runs 7 tutors — a tutor/key hand is a keep even without a cheap play.
        "key_extra": ["Reiterate", "Seething Song", "Narset's Reversal"],   # combo pieces (WIN_LINE = the burn override)
        # lab=bestline (not clock): the all-finishers harvest (Backlog #11) races the burn
        # goldfish AND the Reiterate+Seething Song combo on one game so the gauntlet sees the
        # deck's fastest line (combo ~T9), not just the race goldfish (table >T14).
    },
    "grand_design": {
        "name": "The Grand Design", "stem": "the-grand-design",
        "commander": "Atraxa, Grand Unifier", "lab": ("gd_clock_lab", "clock"),
        "cc": 18, "cc_axes": (5, 5, 5, 3),   # Interaction 4->3: 2026-06-23 ramp swap cut 5 interaction/protection pieces
        "win_line": {"pieces": ["Craterhoof Behemoth"], "override": 8, "fuzzy": True,
                     "line": "Craterhoof overrun (tutorable; reanimate/Pod/Defense cheat it in); Finale X>=10 backup"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 5, "hi_curve": True,
        "mixed": "ramp-gated; Craterhoof now tutorable (Finale was the single point of failure, fixed 2026-06-23)",
    },
    "crystal_sickness": {
        "name": "Crystal Sickness", "stem": "crystal-sickness",
        "commander": "Golbez, Crystal Collector", "lab": ("cs_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Phyrexian Dreadnought"], "fuzzy": True,
                     "line": "Golbez drain off a high-power creature (needs digging + cycles)"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "dev-gated (8 artifacts + fat creature), not pure finding",
    },
    "croak_and_dagger": {
        "name": "Croak and Dagger", "stem": "croak-and-dagger",
        "commander": "Glarb, Calamity's Augur", "lab": None,   # assembly-clock lab (glarb_inevitable_lab); not a decap/table row
        # 2026-07-01: PROMOTED to the "inevitable" topdeck-combo rebuild (Aetherflux/Bolas's
        # Citadel/Sensei's Top). CC re-scored 18 (5/5/4/4) — kill +1 (redundant counter-immune
        # combo, median T9 vs the old single mana-gated Torment) / interaction -1 (dropped
        # Submerge + V.A.T.S. + Spore Frog for combo pieces; 5 counters + Tidal Barracuda remain).
        "cc": 18, "cc_axes": (5, 5, 4, 4),
        "win_line": {"pieces": ["Sensei's Divining Top", "Bolas's Citadel", "Aetherflux Reservoir"],
                     "fuzzy": True,
                     "line": "Sensei's Top + any top-caster (Bolas's Citadel / One with the Multiverse / "
                             "Fortune Teller's Talent / The Reality Chip) + Aetherflux Reservoir -> loop the "
                             "library -> Pay 50: deal 50 (counter-immune); Torment of Hailfire grind backup"},
        "bottleneck": "FINDING", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "redundant 3-category combo (4 enablers x 2 payoffs); ramp -> Torment is the MANA-gated backup",
        "also": ["MANA"],
        # key_extra (2026-07-03 re-tune): one-representative-per-category key_cards hid the combo's
        # actual redundancy (4 enablers x 2 payoffs) from the keep and from the tutor-bridge check.
        "key_extra": ["One with the Multiverse", "Fortune Teller's Talent",
                      "The Reality Chip", "Ancient Cellarspawn"],
    },
    "forced_liquidation": {
        "name": "Forced Liquidation", "stem": "forced-liquidation",
        "commander": "Kefka, Court Mage", "lab": ("kfk_clock_lab", "clock"),
        "cc": 16, "cc_axes": (5, 4, 3, 4),
        "win_line": {"pieces": ["Notion Thief", "Psychosis Crawler", "Windfall"],
                     "line": "Notion Thief + Psychosis Crawler + any wheel -> one-wheel table kill "
                             "(statics fire through Grand Abolisher)"},
        # FINDING: lethal-or-bust assembly — needs 2+ punishers + a wheel before spinning, or it
        # refuels the pod. The Displacer Kitten + Aether Channeler combo is a $0 backup axis only
        # (~1% by T12; never beats the burn — resilience, not the plan).
        # Re-tuned 2026-07-03 (mulligan audit / London experiment): the any-one-key FINDING keep
        # kept lone-wheel refuel-trap hands and measured -5pp vs the land keep on the deck's own
        # burn clock. n_key_needed=2 encodes "never keep a naked wheel/punisher"; the BOARD union
        # (Kefka 5-drop -> reach genuinely bites) keeps the development hands the burn axis rides.
        "bottleneck": "FINDING", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "n_key_needed": 2,
        "mixed": "lethal-or-bust: keep needs 2 key pieces / a tutor / board development — never a naked wheel",
        "also": ["BOARD"],
    },
}


# Non-roster decklists deck_sim must still parse: dismantled decks + the candidate /
# considering builds. These are NOT active-roster facts (no clock lab, no Summary, not in
# the bake-off), so they live here, not in DECKS. Order within this map is load-bearing:
# parse_deck() prefix-matches the FIRST key a stem startswith, so the glarb-hybrid family
# must keep glarb-hybrid before its -final / -b3 siblings (existing behaviour). Active stems
# are emitted first by active_commanders(); none is a prefix of any extra stem (or vice
# versa), so the merge preserves every prefix match.
EXTRA_COMMANDERS = {
    "peace-offering": None,
    "the-loam-cycle": "Teval, the Balanced Scale",
    "diminishing-returns": "Teysa Karlov",   # dismantled 2026-07-08 (was a DECKS row)
    # 2026-06-12 bake-off candidates (decks/considering/) + the two externals
    "insider-trading": "Yuriko, the Tiger's Shadow",
    "hostile-takeover": "Godo, Bandit Warlord",
    "quantitative-easing": "Kinnan, Bonder Prodigy",
    "asset-stripping": "Korvold, Fae-Cursed King",
    # forced-liquidation PROMOTED to the active roster 2026-06-28 (now a DECKS row) — its
    # stem resolves via active_commanders(); leaving it here would break the active-stem
    # prefix invariant (an active stem may not also be an EXTRA key).
    "clive-external": "Clive, Ifrit's Dominant",
    "kefka-external": "Kefka, Court Mage",
    # 2026-06-14 Hashaton benchmark (decks/considering/) — Esper Thoracle variant
    "hashaton-thoracle": "Hashaton, Scarab's Fist",
    # 2026-06-25 Urza mono-U artifact combo-control candidate (decks/considering/)
    "planned-obsolescence": "Urza, Lord High Artificer",
    # 2026-06-13 external Glarb lists under evaluation (decks/considering/) — all Glarb
    "glarb-strong-ext": "Glarb, Calamity's Augur",
    "glarb-mastermind-ext": "Glarb, Calamity's Augur",
    "glarb-croak-dagger-ext": "Glarb, Calamity's Augur",
    "glarb-hybrid": "Glarb, Calamity's Augur",
    "glarb-hybrid-final": "Glarb, Calamity's Augur",
    "glarb-hybrid-b3": "Glarb, Calamity's Augur",
    # 2026-06-16 external Glarb (Yd Freehold / proposals/External Glarb.md) vs Calamity Tax
    "glarb-external-ext": "Glarb, Calamity's Augur",
    # 2026-06-13 lab-run candidates (decks/considering/)
    "berta-wise-extrapolator": "Berta, Wise Extrapolator",
    "najeela-blade-blossom": "Najeela, the Blade-Blossom",
    # 2026-06-18/19 dismantle-3-build-1 candidates (decks/considering/)
    "winota-joiner": "Winota, Joiner of Forces",
    "yawgmoth-liquidation": "Yawgmoth, Thran Physician",
    "sephiroth-liquidation": "Sephiroth, Fabled SOLDIER",
    # 2026-06-18 external BDD Azula combo lists (decks/considering/) — benchmark vs Lightning War
    "bdd-azula-expensive": "Fire Lord Azula",
    "bdd-azula-budget": "Fire Lord Azula",
    # 2026-07-01 external budget YouTube deck under evaluation (decks/considering/) — Boros Cass recursion COMBO
    "cass-budget-combo": "Cass, Hand of Vengeance",
    # 2026-07-04 World Shapers precon (EOC, Hearthhull) evaluation (decks/considering/) —
    # stock box vs the owned-only 19-swap upgrade vs the external $1400 primer build
    "world-shapers-precon": "Hearthhull, the Worldseed",
    "world-shapers-upgraded": "Hearthhull, the Worldseed",
    "world-shapers-external": "Hearthhull, the Worldseed",
    "world-shapers-merged": "Hearthhull, the Worldseed",
    # 2026-07-05: tuned was MISSING here — its 2026-07-04 clock harvest parsed with
    # commander None (Hearthhull shuffled into the library). Curves re-harvested after
    # the fix; see PROP correction note.
    "world-shapers-tuned": "Hearthhull, the Worldseed",
}

# Display names for non-roster decks that deck_sim labels (the rest fall back to the stem).
EXTRA_DISPLAY = {
    "peace-offering": "Peace Offering",
    "the-loam-cycle": "The Loam Cycle",
    "diminishing-returns": "Diminishing Returns",
}


# kill_tree.py decision-tree specs. Kept in their original render order, keyed by the
# DISPLAY slug kill_tree emits (NOT the decklist stem — e.g. "genome-project", no "the-").
# Pure visualization content (oracle-verified in each deck's clock lab + Summary); only the
# 4 encoded decks appear. `reg_slug` ties each back to its DECKS row.
KILL_TREES = {
    "radiation-sickness": {
        "reg_slug": "radiation_sickness",
        "title": "Radiation Sickness — The Wise Mothman",
        "root": "The Wise Mothman resolved<br/>rad counters tick every opponent's main phase",
        "background": ("rad counters + proliferate<br/>(Vorinclex / Tekuthal / Inexorable Tide)",
                       "all-opponent rad drain", "table ~T10", "table"),
        "lines": [
            ("combo", "Mindcrank + Bloodchief Ascension<br/>(3 quest counters live)",
             "infinite mill → drain loop", "table T7", "combo"),
            ("simic", "Simic Ascendancy reaches<br/>20 growth counters",
             "win at your upkeep", "table T8–9", "combo"),
            ("triumph", "Triumph of the Hordes<br/>+ a wide creature board",
             "+1/+1, trample & INFECT → 10 poison", "table T8", "table"),
            ("combat", "counter-grown creatures connect<br/>(fallback)",
             "focus one opponent", "decap T7", "combat"),
        ],
        "stall": "keep ticking rad + stacking counters —<br/>the passive drain closes ~T10",
        "src": "rs_clock_lab.py + Radiation_Sickness_Summary.md",
    },
    "genome-project": {
        "reg_slug": "genome_project",
        "title": "The Genome Project — Kuja, Genome Sorcerer",
        "root": "Kuja resolved — Wizard tokens ping EVERY opponent on each noncreature cast<br/>transforms to Trance Kuja (×2 ALL Wizard damage) at 4 Wizards",
        "background": None,
        "lines": [
            ("oneshot", "Trance Kuja + City on Fire (×3 all dmg)<br/>and/or Harmonic Prodigy / Roaming Throne",
             "12–16+ damage per opponent per spell → one or two casts kill the table", "table T7", "combo"),
            ("storm", "Trance Kuja + 4 Wizard tokens<br/>(Birgi / Storm-Kiln refund the mana)",
             "8 dmg per opponent per noncreature cast → ~5 cheap casts", "table T8", "table"),
            ("gystorm", "stocked graveyard + Mizzix's Mastery<br/>(Dawn Warriors' Legacy) or Underworld Breach",
             "recast every i/s from the yard — each a REAL cast = full pings", "table T7–8", "combo"),
            ("backup", "mana flood (Mana Geyser / Neheb / Jeska's Will)<br/>or 50 life via Aetherflux Reservoir",
             "board-independent table drain / 50-life laser", "table (backup)", "table"),
            ("combat", "Trance Kuja + a Wizard board<br/>(Trance doubles Wizard power) (fallback)",
             "focus one opponent", "decap T7", "combat"),
        ],
        "stall": "build Wizards toward the 4-count transform & stock the yard —<br/>pings need CASTS (no passive drain), so dig for a multiplier + a cheap chain",
        "src": "gp_clock_lab.py + The_Genome_Project_Summary.md",
    },
    "replication-crisis": {
        "reg_slug": "replication_crisis",
        "title": "The Replication Crisis — Satya, Aetherflux Genius",
        "root": "Satya attacking — each attack makes a free token COPY of a nontoken<br/>creature you control + {E}{E} · EVERY line needs Satya to ATTACK (fires on attack, not on connect)",
        "background": None,
        "lines": [
            ("infinite", "Sword of Feast and Famine on Satya<br/>+ Aggravated Assault",
             "combat untaps all lands → infinite combats → infinite tokens + ETBs", "decap T6–7", "combo"),
            ("brudiclad", "Brudiclad + a token pile<br/>+ a fat Satya copy (Inferno Titan)",
             "convert every token into the bomb → lethal alpha (no infinite needed)", "decap T7", "combat"),
            ("adeline", "Adeline + Anointed Procession",
             "~6 humans per attack + doubled Satya token → wide alpha swing", "decap T7–8", "combat"),
            ("conscripts", "Satya copies Zealous Conscripts<br/>(+ Strionic Resonator / Aggravated Assault)",
             "steal the pod's best permanents, one per combat", "disrupt → decap", "enabler"),
            ("grind", "repeated ETB copies (Inferno Titan ping,<br/>Cloudblazer draw, Skyclave exile) (fallback)",
             "grind the pod out over 3–4 combats", "table T10+", "table"),
        ],
        "stall": "Satya must survive as a 3/5 through combat — protect her<br/>(Greaves / Boots / Slip Out the Back) and hold for a safe swing",
        "src": "rc_speed_lab.py + The_Replication_Crisis_Summary.md",
    },
    "lorehold-spirits": {
        "reg_slug": "lorehold_spirits",
        "title": "Lorehold Spirits — Quintorius, History Chaser",
        "root": "Quintorius (planeswalker) resolved<br/>each time cards LEAVE your graveyard → a 3/2 Spirit (one per event)",
        "background": None,
        "lines": [
            ("ult", "Quintorius −4 (ready ~1 turn after landing) + 4+ Spirits<br/>(Akroma's Will / anthems pile on)",
             "Spirits gain double strike + vigilance → lethal alpha across the table", "table T7–9", "combat"),
            ("purphoros", "Purphoros + Anointed Procession<br/>+ a recursion turn (3 events)",
             "2→4 dmg to EACH opp per Spirit ETB → ~12 to each opp passively", "table T7–9", "table"),
            ("moonshaker", "Moonshaker Cavalry ETB<br/>+ a wide Spirit board (Procession / Patchwork)",
             "all creatures gain flying + a counter → one-turn lethal swing on one opp", "decap T7–9", "combat"),
            ("combo", "Reveillark + Karmic Guide + Goblin Bombardment<br/>+ a ≤2-power creature in yard",
             "unbounded sac loop → arbitrary GB damage + arbitrary Spirits", "table T7–8", "combo"),
            ("grind", "Patchwork Banner + Balefire Liege + Tocasia's Welcome<br/>(Quintorius & Moonshaker down) (fallback)",
             "anthem + 3-per-RW-cast chip → 3–4 turn grindout", "table T9–11", "table"),
        ],
        "stall": "run Quintorius +1 to fill the yard + dig; deploy recursion + a multiplier —<br/>every recursion event is a Spirit, so build toward the −4 alpha",
        "src": "lor_clock_lab.py + Lorehold_Spirits_Summary.md",
    },
    "earthbend-the-meta": {
        "reg_slug": "earthbend_the_meta",
        "title": "Earthbend the Meta — Toph, the First Metalbender",
        "root": "Toph resolved — your nontoken artifacts are LANDS (each artifact ETB is a landfall)<br/>end step earthbends a land into a 0/0+counters creature",
        "background": None,
        "lines": [
            ("scute", "Scute Swarm at 6+ lands + Purphoros<br/>(+ Impact Tremors / Cathars' Crusade)",
             "each landfall copies Scute → 2 dmg to EACH opp per body → 20+ to each opp", "table T7–9", "table"),
            ("triumph", "Triumph of the Hordes<br/>+ 3 earthbent lands at 4+ counters",
             "+1/+1, trample & INFECT → 10 poison kills regardless of life", "table T7–9", "table"),
            ("awbo", "All Will Be One + amplifier suite<br/>(Hardened Scales / Earth Crystal / Doubling Season)",
             "each +1/+1 counter placed → that much to ONE opp; earthbend 2 = 12+", "decap T7–9", "combat"),
            ("kyoshi", "Toph, Greatest Earthbender (double strike)<br/>+ 3–4 earthbent lands (8–24 each)",
             "land-creatures swing for lethal double-strike damage on one opp", "decap T7–9", "combat"),
            ("moraug", "Moraug + multiple land drops<br/>+ double-strike land-creatures (fallback)",
             "3–5 extra combat phases → lethal through accumulated steps on one opp", "decap T7–9", "combat"),
        ],
        "stall": "ramp + animate lands each end step, stacking counters under the amplifier suite —<br/>the deck doesn't tutor, so dig for a finisher while Scute snowballs",
        "src": "ebm_clock_lab.py + Earthbend_the_Meta_Summary.md",
    },
    "exiles-return": {
        "reg_slug": "exiles_return",
        "title": "The Exile's Return — Fire Lord Zuko",
        "root": "Fire Lord Zuko resolved<br/>each cast-from-exile + each permanent entering from exile puts +1/+1 on EACH creature you control",
        "background": None,
        "lines": [
            ("counterstack", "blink + cast-from-exile engine running<br/>(Panharmonicon doubles enters-events) → Zuko 7+ power",
             "counter-pumped board + 21 Zuko commander damage in ~3 swings", "decap T7–8", "combat"),
            ("hellkite", "Hellkite Charger + Sozin's Comet<br/>(firebending 5 on all; only Diabolic Intent finds either)",
             "20R combat income pays Hellkite's 5RR → infinite extra combats → table", "table T10", "combo"),
            ("roku", "The Legend of Roku III → Avatar Roku<br/>(4/4 firebending 4)",
             "attacks for 4R, funds dragon-token activations — backup when blink is down", "decap T11+", "combat"),
            ("suntitan", "Sun Titan attacks → return a ≤MV3 permanent<br/>(+ a blink piece to re-loop it) (fallback)",
             "rebuild the engine every attack → grind out, very durable post-wipe", "decap (slow/durable)", "enabler"),
        ],
        "stall": "land an impulse-draw or blinker, then a doubler (Panharmonicon) / repeating blink<br/>(Teleportation Circle, Airbender Ascension, Norin) — pile counters until Zuko swings",
        "src": "er_speed_lab.py + The_Exiles_Return_Summary.md",
    },
    "zero-sum-game": {
        "reg_slug": "zero_sum_game",
        "title": "Zero-Sum Game — Witherbloom, the Balancer",
        "root": "go wide cheaply (dorks / Bitterblossom / Saprolings)<br/>Witherbloom's instant/sorcery affinity discounts your tutors & rituals<br/>(the primary lifeloop is commander-INDEPENDENT)",
        "background": None,
        "lines": [
            ("loop", "a blood-half (Exquisite Blood / Bloodthirsty Conqueror)<br/>+ a vito-half (Vito / Sanguine Bond / Enduring Tenacity / Defiant Bloodlord)<br/>+ any life event (combat, Cauldron Familiar, a sac)",
             "the loop drains the whole table one player at a time, at instant speed", "table T9", "combo"),
            ("chain", "Chain of Smog + Witherbloom Apprentice<br/>(no board, no commander needed)",
             "target yourself → infinite magecraft copies → 1–2 to each opp per copy", "table", "combo"),
            ("affinity", "Witherbloom + 4+ creatures + Sprout Swarm<br/>(or Lab Rats + Phyrexian Altar) + Witherbloom Apprentice",
             "infinite free casts → magecraft drains the table", "table (later)", "combo"),
            ("razaketh", "Razaketh, the Foulblooded + tokens to sacrifice",
             "2 life + a token each → tutor the missing loop piece at instant speed", "enabler", "enabler"),
            ("combat", "Bitterblossom fliers + Tendershoot + Hornet Queen<br/>(fallback)",
             "focus one opponent — irrelevant as a clock, real as loop ignition", "decap T12+", "combat"),
        ],
        "stall": "build a token board (affinity discounts + sac fodder + ignition) and dig<br/>with the tutors for a blood-half + a vito-half — the loop is the deck",
        "src": "wb_clock_lab.py + Zero_Sum_Game_Summary.md",
    },
    "curse-of-the-scarab": {
        "reg_slug": "curse_of_the_scarab",
        "title": "Curse of the Scarab — The Scarab God",
        "root": "The Scarab God resolved (~T5)<br/>flood the board with Zombies (tribal + tokens + reanimation)<br/>Zombie count drives drain, draw & combat",
        "background": ("a wide Zombie board live",
                       "each opponent loses X = Zombies you control, every upkeep (no mana/attack)",
                       "table ~T11", "table"),
        "lines": [
            ("gary", "Gray Merchant of Asphodel ETB<br/>(devotion 6–10; recur via Reanimate / Necromancy / Scarab activated)",
             "each opponent loses your black devotion on ETB; recurs for repeat bursts", "table (fastest non-combo)", "table"),
            ("loop", "Warren Soultrader + Gravecrawler + Plague Belcher<br/>(Rule 0)",
             "sac/recast Gravecrawler loop → each cycle drains 1; up to 39 at 40 life", "table T8+", "combo"),
            ("storm", "Rooftop Storm + Necroduality + Diregraf Colossus",
             "empty a Zombie hand for free → 12+ Zombies → 12+ Scarab drain next upkeep", "table T9–10", "table"),
            ("combat", "lord-pumped Zombies (Death Baron / Warchief / Mikaeus)<br/>+ Cyclonic Rift (overload) clears blockers (fallback)",
             "focus-fire one opponent with a 4/4+ wide board", "decap T8", "combat"),
        ],
        "stall": "grow the Zombie count + draw (Kindred Discovery); the upkeep drain is passive<br/>inevitability — board wipes feed the yard for Living Death, so don't fear them",
        "src": "cos_clock_lab.py + Curse_of_the_Scarab_Summary.md",
    },
    "bumbleflower": {
        "reg_slug": "bumbleflower",
        "title": "Ms. Bumbleflower — Ms. Bumbleflower",
        "root": "Ms. Bumbleflower online (~T3–4)<br/>each spell you cast: an opp draws, +1/+1 counter (+flying) on a creature;<br/>the 2nd cast each turn → you draw two",
        "background": None,
        "lines": [
            ("jolrael", "Jolrael, Mwonvuli Recluse + a full hand + a board<br/>(Cats / payoff creatures / stolen bodies)",
             "Jolrael's 4GG pump sets your team to X/X (X = cards in hand) → 8–12-power alpha", "decap T8", "combat"),
            ("willbreaker", "Willbreaker + aim Bumbleflower's counter at an opp's creature each cast",
             "steal a creature every spell (it flies in that turn) → swing with their own board", "decap (grindy)", "combat"),
            ("counters", "pile +1/+1 counters & flying on one carrier each cast<br/>(optionally vacuum them into Sin, Unending Cataclysm) (fallback)",
             "a single evasive counter-grown threat flies over", "decap T8+ (slowest)", "combat"),
        ],
        "stall": "out-value the table — chain cantrips for the 2nd-cast draw-two, deploy draw payoffs,<br/>hold up the deep counter/removal suite; the kill is slow & combat-only, so close from dominance",
        "src": "bmf_clock_lab.py + Ms_Bumbleflower_Summary.md",
    },
    "eldrazi-stampede-chaos": {
        "reg_slug": "eldrazi_stampede",
        "title": "Eldrazi Stampede Chaos — Maelstrom Wanderer",
        "root": "Maelstrom Wanderer cast (5GUR)<br/>two cascades into nonland MV<8 + creatures you control have haste",
        "background": None,
        "lines": [
            ("ghalta", "Ghalta, Primal Hunger<br/>(a wide Eldrazi/power board drops its cost toward GG)",
             "12/12 trample lands cheap → annihilator + trample close", "decap T5–7", "combat"),
            ("wanderer", "Wanderer's two hasty cascades<br/>+ its own 7 power + beater pile",
             "15–25 turn-of-cast → focus one opponent", "decap T8", "combat"),
            ("craterhoof", "Craterhoof Behemoth (8 mana, haste)<br/>+ 8 creatures on board",
             "+X/+X & TRAMPLE → swing distributes across the table", "table T12", "table"),
            ("sunbird", "Sunbird's Invocation resolved<br/>then hardcast a big Eldrazi from hand",
             "free chained spells off each cast → snowball to lethal", "table T6+", "enabler"),
            ("ulamog", "Ulamog, the Ceaseless Hunger hardcast (10 mana)<br/>(fallback)",
             "attacks exile 20 cards → mill out (uncounterable back-up)", "table T8+ (slow)", "table"),
        ],
        "stall": "re-ramp toward the 8-mana Wanderer cast and a wide board —<br/>no passive drain; the Craterhoof table-alpha is what closes (~T12)",
        "src": "esc_clock_lab.py + Eldrazi_Stampede_Chaos_Summary.md",
    },
    "dark-lords-army": {
        "reg_slug": "dark_lords_army",
        "title": "The Dark Lord's Army — Sauron, the Dark Lord",
        "root": "Sauron resolved — engine is OPPONENT-DRIVEN<br/>every opponent spell amasses Orcs; the draw-punishers drain on every opponent draw",
        "background": ("Sheoldred + Underworld Dreams + Bowmasters<br/>(Wound Reflection doubles the end-step loss)",
                       "all-opponent drain on every opponent draw", "table T12 (typical pod)", "table"),
        "lines": [
            ("army", "Army amassed by opponent spells<br/>+ evasion (Cover of Darkness / Rogue's Passage)",
             "10+ power unblockable Orc Army → focus one opponent in 2–3 swings", "decap T9", "combat"),
            ("gary", "Gray Merchant of Asphodel ETB<br/>(high black devotion from the engine)",
             "each opponent loses your black devotion on ETB → burst close", "table (burst)", "table"),
            ("aristocrats", "Dictate of Erebos + Goblin Bombardment + Pitiless Plunderer<br/>(sac the Army, it reforms free)",
             "forced opponent sacs + Treasure → relentless grind", "grind (relentless)", "enabler"),
            ("reset", "Living Death / Reanimate / Agadeem's Awakening<br/>(Ring discards stock the yard)",
             "reanimate Sheoldred / Gray Merchant / Yawgmoth → re-fire the drain", "reset → table", "enabler"),
        ],
        "stall": "let the pod play the game — amass + drain feed on THEIR spells and draws;<br/>deploy engine pieces and hold up interaction (faster vs active pods)",
        "src": "dla_clock_lab.py + The_Dark_Lord_s_Army_Summary.md",
    },
    "lightning-war": {
        "reg_slug": "lightning_war",
        "title": "Lightning War — Fire Lord Azula",
        "root": "Fire Lord Azula attacking — every spell you cast that combat is COPIED<br/>(3× with Twinning Staff); she only needs to be DECLARED as an attacker, not connect",
        "background": None,
        "lines": [
            ("combo", "Reiterate + Seething Song (infinite red mana)<br/>or Narset's Reversal + Frantic Search / Turnabout / Storm-Kiln",
             "infinite mana/draw → Torment of Hailfire / multikicked Comet Storm = dead table", "table T9", "combo"),
            ("xspell", "Azula attacking + an X-finisher (Crackle / Comet Storm)<br/>doubled by Twinning Staff / Galvanic Iteration",
             "Crackle X=3 ×Twinning = 45 to each opp; chip from Guttersnipe / Vivi pingers", "table T11 / decap T10", "table"),
            ("banefire", "Banefire X≥5 (uncounterable, can't be prevented)<br/>copied by Azula + a flash enabler",
             "delete the counter-wall player — ignores countermagic", "decap", "combat"),
            ("storm", "flash enabler + Yawgmoth's Will / Past in Flames / Invoke Calamity<br/>(replay the yard in Azula's combat)",
             "every replayed spell copied → 40+ damage (non-infinite, dies to gy hate)", "table (fragile backup)", "enabler"),
        ],
        "stall": "tutor toward one loop piece + a sink and kill on YOUR turn<br/>(Abolisher can't stop a kill cast in your own combat); burn doubles as removal — delete Grand Abolisher on sight",
        "src": "lw_clock_lab.py + lw_combo_lab.py + Lightning_War_Summary.md",
    },
    "grand-design": {
        "reg_slug": "grand_design",
        "title": "The Grand Design — Atraxa, Grand Unifier",
        "root": "Atraxa cast — ETB reveals top 10, take one of each card type (nets 5–7 cards)<br/>fuels reanimation + flicker + Birthing Pod creature chain",
        "background": None,
        "lines": [
            ("crater", "Craterhoof Behemoth + a board<br/>(hardcast 8, or Pod / Defense / reanimate / Finale X≥8 cheat it in)",
             "ETB haste: creatures gain TRAMPLE + +X/+X → overrun (reliably decaps; table slower)", "decap T9", "combat"),
            ("defense", "Defense of the Heart resolves<br/>(any opponent has 3+ creatures at your upkeep)",
             "free: search 2 creatures onto battlefield (Craterhoof straight to play → immediate kill)", "decap T9", "enabler"),
            ("razaketh", "Razaketh reanimated (Reanimate ~1 mana)<br/>+ creatures to sacrifice",
             "sac fodder, pay 2 life: tutor any card → grab Craterhoof / Finale → kill next turn", "decap T10–11", "enabler"),
            ("finale", "Finale of Devastation X≥10 (12 mana, untutorable sorcery)<br/>+ a creature in play",
             "+X/+X & haste to all — but no trample, so it FOCUS-FIRES one opponent", "decap T11 (~9% of games)", "combat"),
            ("combat", "Atraxa swinging (7/7 flying, vigilance, deathtouch, lifelink)<br/>+ a developed board (fallback)",
             "incremental combat — 96% of the deck's decaps; or 21 commander damage", "decap T10 / table T12+", "combat"),
        ],
        "stall": "build the engine (reanimate a bomb T3–4, cast Atraxa T6–7, or start a Pod chain) —<br/>the deck grinds at sorcery speed; protect the kill turn behind a counter or Teferi (protection is thin)",
        "src": "gd_clock_lab.py + The_Grand_Design_Summary.md",
    },
    "crystal-sickness": {
        "reg_slug": "crystal_sickness",
        "title": "Crystal Sickness — Golbez, Crystal Collector",
        "root": "Golbez online with 8+ artifacts<br/>each end step return a creature from your yard; with 8+ artifacts EACH opponent loses life = its power",
        "background": None,
        "lines": [
            ("dreadnought", "Phyrexian Dreadnought in the yard (12 power)<br/>recur + re-bin for 1 mana each turn",
             "12 drain to each opponent every end step → ~4 cycles", "table T13", "table"),
            ("master", "Master of Etherium in the yard<br/>(= your artifact count; reads in graveyard)",
             "10+ drain to each opponent, scales with the 8-artifact board", "table T13", "table"),
            ("tezzeret", "Tezzeret, Master of the Bridge +2<br/>(X = artifacts, to EACH opponent, once/turn)",
             "stacks with Golbez → 20+ life loss per opp per turn", "table ~T11", "table"),
            ("thopters", "Urza's Construct (= artifacts) / 6+ flying Thopters<br/>(3/3 with Master + Stridehangar)",
             "focus-fire one opponent in the air (decap leads by ~2)", "decap T11", "combat"),
            ("mirrodin", "Mirrodin Besieged (Phyrexian)<br/>+ 15 artifact cards in YOUR graveyard (fallback)",
             "target opponent loses the game each end step (dodges lifegain/fog)", "table T13+ (slowest)", "table"),
        ],
        "stall": "deploy artifacts toward the 8-count and bin a drain bomb (Dreadnought self-sac / Troll swampcycle / surveil);<br/>refill the hand — the engine is card draw, not the curve",
        "src": "cs_clock_lab.py + Crystal_Sickness_Summary.md",
    },
    "croak-and-dagger": {
        "reg_slug": "croak_and_dagger",
        "title": "Croak and Dagger — Glarb, Calamity's Augur",
        "root": "Glarb + Sensei's Divining Top online ({T}: draw a card, put Top back on top)<br/>a no-MV-restriction top-caster lets you RECAST Top off the library each loop → chain the deck",
        "background": None,
        "lines": [
            ("aetherflux", "Sensei's Top + a top-caster (Bolas's Citadel / One with the Multiverse /<br/>Fortune Teller's L2 / Reality Chip) + Aetherflux Reservoir",
             "loop Top casts → bank 50+ life → Pay 50: deal 50 to each opponent (a counter-immune ability)", "table T9", "combo"),
            ("cellarspawn", "same loop, Ancient Cellarspawn as the payoff<br/>(drain on each under-costed cast)",
             "every free / discounted Top recast drains an opponent → table (redundant 2nd payoff)", "table T9", "combo"),
            ("tutor", "topdeck tutors (Insidious Dreams / Emergent Ultimatum / Scheming Symmetry)<br/>stack the missing category on top for Glarb / Citadel",
             "assemble the 3-category loop a turn or two sooner (GSZ / Chord / Finale fetch the creature pieces)", "enabler → table T9", "enabler"),
            ("torment", "Torment of Hailfire X=12+ (~14 mana via Cabal Coffers + Urborg)<br/>— the board-independent grind backup when the combo bricks (~10%)",
             "each opponent: 12× lose-3 / sac / discard → lethal table drain", "table (backup)", "table"),
            ("combat", "Archon of Cruelty / Massacre Wurm value + Glarb beats<br/>(fallback)",
             "focus one opponent", "decap (grind)", "combat"),
        ],
        "stall": "dig with Glarb surveil 2 + Top + Sylvan toward Top + any enabler + any payoff;<br/>combo on YOUR turn behind the counter suite + Tidal Barracuda (opponents can't cast on your turn)",
        "src": "glarb_inevitable_lab.py + Croak_And_Dagger_Summary.md",
    },
    "forced-liquidation": {
        "reg_slug": "forced_liquidation",
        "title": "Forced Liquidation — Kefka, Court Mage",
        "root": "Grixis 'forced draw' punisher shell — static draw/discard punishers in play<br/>the kill is a WHEEL cast on YOUR turn feeding STATICS, so it fires THROUGH Grand Abolisher",
        "background": None,
        "lines": [
            ("notion", "Notion Thief + Psychosis Crawler + any wheel<br/>(Niv-Mizzet, Parun = redundant version)",
             "you draw ~28 (your 7 + ~21 redirected) → each opponent loses ~28 AND draws nothing", "table T9", "table"),
            ("wheel", "2+ opponent-draw punishers (Underworld Dreams / Fate Unraveler / Sheoldred / Ob Nixilis)<br/>+ a wheel · Bloodletter of Aclazotz doubles it",
             "each opponent draws 7 → ~14–28 life loss each (lethal-or-bust — never spin on one)", "table T9", "table"),
            ("peer", "Peer into the Abyss aimed at one opponent<br/>with a draw-punisher out",
             "they draw ~half their library → that much damage + lose half their life", "decap T8", "combat"),
            ("kitten", "Displacer Kitten + Aether Channeler + Sol Ring + Mana Vault<br/>+ Niv-Mizzet or Psychosis Crawler (all in play)",
             "infinite ETB → infinite draw → lethal (Abolisher-proof, commander-independent)", "table ~1% by T12 (slow backup)", "combo"),
        ],
        "stall": "assemble + protect ~2 punishers to the wheel turn (lethal-or-bust — a half-loaded wheel refuels the pod);<br/>kill Grand Abolisher / draw-deniers on sight, and don't stack Notion Thief with the opponent-draw punishers",
        "src": "kfk_clock_lab.py + Forced_Liquidation_Summary.md",
    },
}


# --------------------------------------------------------------------------- helpers
def _version_key(path, stem):
    """Chronological sort key for a dated decklist filename so the NEWEST sorts last.

    The trailing `YYYYMMDD[-HHMMSS]` is parsed as a tuple of ints. A same-date file
    WITH a time suffix (e.g. ...-20260623-215731.txt) is later in the day than the
    bare date (...-20260623.txt): the longer int-tuple sorts after the shorter, so
    the timestamped re-cut wins the tie — matching the real croak-and-dagger
    history (the bare-date file was archived, the 21:57:31 cut went live the same
    day). Plain string sort got this backwards because '.' (0x2E) > '-' (0x2D),
    ranking the bare-date file last. The filename is the final, fully-deterministic
    tiebreaker for identical timestamps."""
    nums = tuple(int(g) for g in re.findall(r"\d+", path.name[len(stem):]))
    return (nums, path.name)


def resolve_deck(stem):
    """Newest decks/{stem}-*.txt (the dated filename is the version history), or None.

    Same-date ties are won by the more specific (timestamped) file."""
    hits = sorted(DECK_DIR.glob(f"{stem}-*.txt"), key=lambda p: _version_key(p, stem))
    return hits[-1] if hits else None


def fb_decks():
    """framework_bakeoff.DECKS shape: slug -> (name, stem, cc, cc_axes). Order preserved."""
    return {s: (d["name"], d["stem"], d["cc"], d["cc_axes"]) for s, d in DECKS.items()}


def win_lines():
    """framework_bakeoff.WIN_LINE shape: slug -> win_line dict."""
    return {s: d["win_line"] for s, d in DECKS.items()}


def judgment():
    """keep_spec.JUDGMENT shape: slug -> (bottleneck, min_lands, max_lands, hi_curve, mixed)."""
    return {s: (d["bottleneck"], d["min_lands"], d["max_lands"], d["hi_curve"], d["mixed"])
            for s, d in DECKS.items()}


def also():
    """keep_spec.ALSO shape: slug -> [secondary axes] — only the two-line decks (those with `also`)."""
    return {s: d["also"] for s, d in DECKS.items() if d.get("also")}


def active_commanders():
    """deck_sim COMMANDERS contribution: stem -> commander, for the active roster."""
    return {d["stem"]: d["commander"] for d in DECKS.values()}


def active_display():
    """deck_sim DISPLAY contribution: stem -> display name, for the active roster."""
    return {d["stem"]: d["name"] for d in DECKS.values()}


def kill_trees():
    """kill_tree.DECKS shape: display-slug -> spec (title/root/background/lines/stall/src),
    in render order. The `reg_slug` cross-reference is dropped (kill_tree doesn't use it)."""
    return {slug: {k: v for k, v in spec.items() if k != "reg_slug"}
            for slug, spec in KILL_TREES.items()}


def deck_key_index():
    """deck_key (== stem) -> slug, for harvesters that key by the decklist stem."""
    return {d["stem"]: s for s, d in DECKS.items()}
