#!/usr/bin/env python3
"""deck_registry.py — the single source of truth for per-deck STATIC metadata.

Before this module the same per-deck facts were hand-typed across five files: the
identity tuple (slug / display name / decklist stem / commander) lived in
framework_bakeoff.DECKS, deck_sim.COMMANDERS+DISPLAY, pod_gauntlet.CLOCKS and
kill_tree.DECKS; the win line in framework_bakeoff.WIN_LINE; the mulligan judgment in
keep_spec.JUDGMENT/ALSO. Adding a deck meant editing all of them. Now each consumer
READS this registry, so a new deck is one row here (+ its bespoke `*_clock_lab.py`,
the one irreducible per-deck artifact — its turn-by-turn kill logic is code, not data).

What this module deliberately does NOT own:
  - the bespoke kill models / clock grids inside each `*_clock_lab.py` (irreducible;
    and the labs PIN a dated decklist for reproducibility, unlike the latest-resolving
    consumers here — so their paths stay local).
  - the harvested clock CURVES (grid/decap/table/med/never) in pod_gauntlet.CLOCKS and
    analysis/pod_gauntlet_clocks.json — those are lab OUTPUTS, regenerated by
    `pod_gauntlet.py --refresh`, not identity.
  - the oracle P(win) snapshots (RICHER_ORACLE / INTERACTION_ORACLE in
    framework_bakeoff) — also derived lab outputs.

Pure data + tiny helpers, NO heavy imports (no oracle load, no other local module), so
it sits below every consumer with no import cycles. Keyed by slug (underscore form);
each row's `stem` is the decklist filename prefix (== deck_sim's deck_key). Row ORDER is
load-bearing — it is the column order of the framework bake-off — so keep it stable.

Consumers and the accessor they use:
  framework_bakeoff  fb_decks()  win_lines()
  keep_spec          judgment()  also()
  deck_sim           active_commanders()  active_display()
  pod_gauntlet       lab pointer (DECKS[slug]["lab"])
  kill_tree          kill_trees()
  report.py          the whole row
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECK_DIR = ROOT / "decks"


# Row schema (per slug):
#   name        display name              stem        decklist filename prefix (= deck_key)
#   commander   command-zone card name    lab         (module, mode) of its clock lab, or None
#   cc          Conversion Check total    cc_axes     (core, kill, durability, interaction) or None
#   win_line    cheapest documented kill line (BDD mana-budget; pieces/override/fuzzy/line)
#   bottleneck  FINDING | MANA | BOARD    min/max_lands  mulligan keep band (closed)
#   hi_curve    tolerate a 4-land no-ramp keep            mixed   second-axis note (or None)
#   also        union-keep secondary axes (only present on genuinely two-line decks)
DECKS = {
    "genome_project": {
        "name": "The Genome Project", "stem": "the-genome-project",
        "commander": "Kuja, Genome Sorcerer", "lab": ("gp_clock_lab", "clock"),
        "cc": 15, "cc_axes": (4, 4, 3, 4),
        "win_line": {"pieces": ["City on Fire"], "fuzzy": True,
                     "line": "Trance Kuja + City on Fire (x3 dmg) — 1-2 casts kill the table"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "radiation_sickness": {
        "name": "Radiation Sickness", "stem": "radiation-sickness",
        "commander": "Wise Mothman", "lab": ("rs_clock_lab", "clock"),
        "cc": 18, "cc_axes": (5, 5, 4, 4),
        "win_line": {"pieces": ["Mindcrank", "Bloodchief Ascension"], "needs_cmdr": False,
                     "line": "Mindcrank + Bloodchief Ascension infinite (commander-independent)"},
        # Re-tagged FINDING->BOARD 2026-06-16: the FINDING keep dug for the Mindcrank/Bloodchief
        # combo (a SIDE line) and slowed the real clock (counter-grown board) -9pp at front7. The
        # board IS the fast decap; BOARD keep (Mothman on curve + early play) matches it. Union
        # (combo OR board) via `also`.  (analysis/Plan_Aware_Mulligan_2026-06-16.md)
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "combo is a side line; fast clock = counter-board (was FINDING, -9pp front7)",
        "also": ["FINDING"],   # BOARD primary (counter-grown board) + Mindcrank/Bloodchief combo upside
    },
    "replication_crisis": {
        "name": "The Replication Crisis", "stem": "the-replication-crisis",
        "commander": "Satya, Aetherflux Genius", "lab": ("rc_speed_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Sword of Feast and Famine", "Aggravated Assault"],
                     "line": "Satya + Sword of F&F + Aggravated Assault -> infinite combats"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "commander-gated; trigger on ATTACK (haste) — protect to swing",
        "also": ["FINDING"],   # BOARD primary (Satya attack) + Sword/Aggravated combo upside
    },
    "lorehold_spirits": {
        "name": "Lorehold Spirits", "stem": "lorehold-spirit",
        "commander": "Quintorius, History Chaser", "lab": ("lor_clock_lab", "clock"),
        "cc": 18, "cc_axes": (5, 5, 4, 4),
        "win_line": {"pieces": ["Reveillark", "Karmic Guide", "Goblin Bombardment"],
                     "line": "Reveillark + Karmic Guide + Goblin Bombardment loop (table)"},
        # Re-tagged FINDING->BOARD 2026-06-16: the 3-card Reveillark loop is a side line; the fast
        # decap is spirits/Quintorius value, a BOARD clock (-4pp front7 under the FINDING keep).
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "3-card loop is a side line; fast clock = spirits/Quintorius (was FINDING, -4pp front7)",
        "also": ["FINDING"],   # BOARD primary (spirits/Quintorius) + 3-card Reveillark loop upside
    },
    "earthbend_the_meta": {
        "name": "Earthbend the Meta", "stem": "earthbend-the-meta",
        "commander": "Toph, the First Metalbender", "lab": ("ebm_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Triumph of the Hordes"], "fuzzy": True,
                     "line": "Triumph of the Hordes one-card closer from an earthbent board"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "lands-matter board also a payoff axis",
    },
    "exiles_return": {
        "name": "The Exile's Return", "stem": "the-exiles-return",
        "commander": "Fire Lord Zuko", "lab": ("er_speed_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Hellkite Charger"], "fuzzy": True,
                     "line": "Hellkite Charger + firebending extra-combats"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "zero_sum_game": {
        "name": "Zero-Sum Game", "stem": "zero-sum-game",
        "commander": "Witherbloom, the Balancer", "lab": ("wb_clock_lab", "clock"),
        "cc": None, "cc_axes": None,
        "win_line": {"pieces": ["Exquisite Blood", "Sanguine Bond"], "needs_cmdr": False,
                     "line": "Exquisite Blood + Sanguine Bond loop + any life event (cmdr-indep.)"},
        "bottleneck": "FINDING", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "curse_of_the_scarab": {
        "name": "Curse of the Scarab", "stem": "curse-of-the-scarab",
        "commander": "The Scarab God", "lab": ("cos_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Gray Merchant of Asphodel"], "fuzzy": True,
                     "line": "Gray Merchant burst drain off black devotion"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 5, "hi_curve": False, "mixed": None,
    },
    "bumbleflower": {
        "name": "Ms. Bumbleflower", "stem": "this-bunny-goes-to-market",
        "commander": "Ms. Bumbleflower", "lab": ("bmf_clock_lab", "clock"),
        "cc": 15, "cc_axes": (4, 3, 3, 5),
        "win_line": {"pieces": ["Jolrael, Mwonvuli Recluse"], "fuzzy": True,
                     "line": "Jolrael alpha strike (lands -> X/X, X = hand size)"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
    "eldrazi_stampede": {
        "name": "Eldrazi Stampede Chaos", "stem": "eldrazi-stampede-chaos",
        "commander": "Maelstrom Wanderer", "lab": ("esc_clock_lab", "clock"),
        "cc": 14, "cc_axes": (4, 4, 3, 3),
        "win_line": {"pieces": ["Craterhoof Behemoth"], "fuzzy": True,
                     "line": "Craterhoof alpha over an Eldrazi/ramp board"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 5, "hi_curve": True, "mixed": None,
    },
    "dark_lords_army": {
        "name": "The Dark Lord's Army", "stem": "the-dark-lords-army",
        "commander": "Sauron, the Dark Lord", "lab": ("dla_clock_lab", "pod"),
        "cc": 19, "cc_axes": (5, 4, 5, 5),
        "win_line": {"pieces": ["Gray Merchant of Asphodel"], "fuzzy": True,
                     "line": "Sheoldred/Underworld Dreams/Wound Reflection drain + Gary close"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 5, "hi_curve": False, "mixed": None,
    },
    "diminishing_returns": {
        "name": "Diminishing Returns", "stem": "diminishing-returns",
        "commander": "Teysa Karlov", "lab": ("dr_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Gravecrawler", "Phyrexian Altar"],
                     "line": "Gravecrawler + Phyrexian Altar + sac/drain loop (Teysa doubles)"},
        "bottleneck": "FINDING", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "aristocrats board fallback (death volume) not in predicate — watch",
        "also": ["BOARD"],   # FINDING primary (Gravecrawler combo) + aristocrats death-volume board
    },
    "lightning_war": {
        "name": "Lightning War", "stem": "lightning-war",
        "commander": "Fire Lord Azula", "lab": ("lw_clock_lab", "clock"),
        "cc": 19, "cc_axes": (5, 5, 4, 5),
        "win_line": {"pieces": ["Banefire"], "override": 14, "fuzzy": True,
                     "line": "X-burn finisher (Banefire/Crackle); ~14 mana from-40 lethal"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "flips at Azula: deploy CMC4 cmdr -> cheap-spell copy engine",
    },
    "grand_design": {
        "name": "The Grand Design", "stem": "the-grand-design",
        "commander": "Atraxa, Grand Unifier", "lab": ("gd_clock_lab", "clock"),
        "cc": 19, "cc_axes": (5, 5, 5, 4),
        "win_line": {"pieces": ["Finale of Devastation"], "override": 12, "fuzzy": True,
                     "line": "Finale of Devastation X>=10 (sorcery funnel); combat backup"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 5, "hi_curve": True,
        "mixed": "also FINDING (Finale = single point of failure)",
    },
    "crystal_sickness": {
        "name": "Crystal Sickness", "stem": "crystal-sickness",
        "commander": "Golbez, Crystal Collector", "lab": ("cs_clock_lab", "clock"),
        "cc": 17, "cc_axes": (5, 4, 4, 4),
        "win_line": {"pieces": ["Phyrexian Dreadnought"], "fuzzy": True,
                     "line": "Golbez drain off a high-power creature (needs digging + cycles)"},
        "bottleneck": "BOARD", "min_lands": 2, "max_lands": 4, "hi_curve": False,
        "mixed": "dev-gated (8 artifacts + fat creature), not pure finding",
    },
    "croak_and_dagger": {
        "name": "Croak and Dagger", "stem": "croak-and-dagger",
        "commander": "Glarb, Calamity's Augur", "lab": None,   # multi-variant lab; base not printed
        "cc": 18, "cc_axes": (5, 4, 4, 5),
        "win_line": {"pieces": ["Torment of Hailfire"], "override": 14, "fuzzy": True,
                     "line": "Torment of Hailfire X=12+ (requires ~14 total mana)"},
        "bottleneck": "MANA", "min_lands": 2, "max_lands": 4, "hi_curve": False, "mixed": None,
    },
}


# Non-roster decklists deck_sim must still parse: dismantled decks + the candidate /
# considering builds. These are NOT active-roster facts (no clock lab, no Summary, not in
# the bake-off), so they live here, not in DECKS. Order within this map is load-bearing:
# parse_deck() prefix-matches the FIRST key a stem startswith, so the glarb-hybrid family
# must keep glarb-hybrid before its -final / -b3 siblings (existing behaviour). Active stems
# are emitted first by active_commanders(); none is a prefix of any extra stem (or vice
# versa), so the merge preserves every prefix match.
EXTRA_COMMANDERS = {
    "peace-offering": None,
    "the-loam-cycle": "Teval, the Balanced Scale",
    # 2026-06-12 bake-off candidates (decks/considering/) + the two externals
    "insider-trading": "Yuriko, the Tiger's Shadow",
    "hostile-takeover": "Godo, Bandit Warlord",
    "quantitative-easing": "Kinnan, Bonder Prodigy",
    "asset-stripping": "Korvold, Fae-Cursed King",
    "forced-liquidation": "Kefka, Court Mage",
    "clive-external": "Clive, Ifrit's Dominant",
    "kefka-external": "Kefka, Court Mage",
    # 2026-06-14 Hashaton benchmark (decks/considering/) — Esper Thoracle variant
    "hashaton-thoracle": "Hashaton, Scarab's Fist",
    # 2026-06-13 external Glarb lists under evaluation (decks/considering/) — all Glarb
    "glarb-strong-ext": "Glarb, Calamity's Augur",
    "glarb-mastermind-ext": "Glarb, Calamity's Augur",
    "glarb-croak-dagger-ext": "Glarb, Calamity's Augur",
    "glarb-hybrid": "Glarb, Calamity's Augur",
    "glarb-hybrid-final": "Glarb, Calamity's Augur",
    "glarb-hybrid-b3": "Glarb, Calamity's Augur",
    # 2026-06-16 external Glarb (Yd Freehold / proposals/External Glarb.md) vs Calamity Tax
    "glarb-external-ext": "Glarb, Calamity's Augur",
    # 2026-06-13 lab-run candidates (decks/considering/)
    "berta-wise-extrapolator": "Berta, Wise Extrapolator",
    "najeela-blade-blossom": "Najeela, the Blade-Blossom",
    # 2026-06-18/19 dismantle-3-build-1 candidates (decks/considering/)
    "winota-joiner": "Winota, Joiner of Forces",
    "yawgmoth-liquidation": "Yawgmoth, Thran Physician",
    "sephiroth-liquidation": "Sephiroth, Fabled SOLDIER",
    # 2026-06-18 external BDD Azula combo lists (decks/considering/) — benchmark vs Lightning War
    "bdd-azula-expensive": "Fire Lord Azula",
    "bdd-azula-budget": "Fire Lord Azula",
}

# Display names for non-roster decks that deck_sim labels (the rest fall back to the stem).
EXTRA_DISPLAY = {
    "peace-offering": "Peace Offering",
    "the-loam-cycle": "The Loam Cycle",
}


# kill_tree.py decision-tree specs. Kept in their original render order, keyed by the
# DISPLAY slug kill_tree emits (NOT the decklist stem — e.g. "genome-project", no "the-").
# Pure visualization content (oracle-verified in each deck's clock lab + Summary); only the
# 4 encoded decks appear. `reg_slug` ties each back to its DECKS row.
KILL_TREES = {
    "radiation-sickness": {
        "reg_slug": "radiation_sickness",
        "title": "Radiation Sickness — The Wise Mothman",
        "root": "The Wise Mothman resolved<br/>rad counters tick every opponent's main phase",
        "background": ("rad counters + proliferate<br/>(Vorinclex / Tekuthal / Inexorable Tide)",
                       "all-opponent rad drain", "table ~T10", "table"),
        "lines": [
            ("combo", "Mindcrank + Bloodchief Ascension<br/>(3 quest counters live)",
             "infinite mill → drain loop", "table T7", "combo"),
            ("simic", "Simic Ascendancy reaches<br/>20 growth counters",
             "win at your upkeep", "table T8–9", "combo"),
            ("triumph", "Triumph of the Hordes<br/>+ a wide creature board",
             "+1/+1, trample & INFECT → 10 poison", "table T8", "table"),
            ("combat", "counter-grown creatures connect<br/>(fallback)",
             "focus one opponent", "decap T7", "combat"),
        ],
        "stall": "keep ticking rad + stacking counters —<br/>the passive drain closes ~T10",
        "src": "rs_clock_lab.py + Radiation_Sickness_Summary.md",
    },
    "diminishing-returns": {
        "reg_slug": "diminishing_returns",
        "title": "Diminishing Returns — Teysa Karlov",
        "root": "Teysa Karlov online<br/>every death trigger fires TWICE",
        "background": None,
        "lines": [
            ("loop", "Gravecrawler + Phyrexian Altar<br/>+ a sac outlet",
             "infinite deaths → drain (deterministic)", "table T9+", "combo"),
            ("gary", "Gray Merchant of Asphodel<br/>+ heavy black devotion",
             "ETB drain ×2", "table", "table"),
            ("kokusho", "Kokusho, the Evening Star<br/>+ a sac outlet",
             "5-drain ×2 each death cycle", "table", "table"),
            ("living", "Living Death<br/>(mass reanimation)",
             "refill board → re-fire every death", "reset → table", "table"),
            ("razaketh", "Razaketh, the Foulblooded<br/>+ fodder to sacrifice",
             "tutor the missing piece of any line", "enabler", "enabler"),
            ("combat", "wide token board swings<br/>(fallback)",
             "focus one opponent", "decap T9", "combat"),
        ],
        "stall": "grind deaths — the table drain is slow (T12+);<br/>this deck disrupts, it doesn't race",
        "src": "dr_clock_lab.py + Diminishing_Returns_Summary.md",
    },
    "genome-project": {
        "reg_slug": "genome_project",
        "title": "The Genome Project — Kuja, Genome Sorcerer",
        "root": "Kuja resolved — Wizard tokens ping EVERY opponent on each noncreature cast<br/>transforms to Trance Kuja (×2 ALL Wizard damage) at 4 Wizards",
        "background": None,
        "lines": [
            ("oneshot", "Trance Kuja + City on Fire (×3 all dmg)<br/>and/or Harmonic Prodigy / Roaming Throne",
             "12–16+ damage per opponent per spell → one or two casts kill the table", "table T7", "combo"),
            ("storm", "Trance Kuja + 4 Wizard tokens<br/>(Birgi / Storm-Kiln refund the mana)",
             "8 dmg per opponent per noncreature cast → ~5 cheap casts", "table T8", "table"),
            ("gystorm", "stocked graveyard + Mizzix's Mastery<br/>(Dawn Warriors' Legacy) or Underworld Breach",
             "recast every i/s from the yard — each a REAL cast = full pings", "table T7–8", "combo"),
            ("backup", "mana flood (Mana Geyser / Neheb / Jeska's Will)<br/>or 50 life via Aetherflux Reservoir",
             "board-independent table drain / 50-life laser", "table (backup)", "table"),
            ("combat", "Trance Kuja + a Wizard board<br/>(Trance doubles Wizard power) (fallback)",
             "focus one opponent", "decap T7", "combat"),
        ],
        "stall": "build Wizards toward the 4-count transform & stock the yard —<br/>pings need CASTS (no passive drain), so dig for a multiplier + a cheap chain",
        "src": "gp_clock_lab.py + The_Genome_Project_Summary.md",
    },
    "replication-crisis": {
        "reg_slug": "replication_crisis",
        "title": "The Replication Crisis — Satya, Aetherflux Genius",
        "root": "Satya attacking — each attack makes a free token COPY of a nontoken<br/>creature you control + {E}{E} · EVERY line needs Satya to ATTACK (fires on attack, not on connect)",
        "background": None,
        "lines": [
            ("infinite", "Sword of Feast and Famine on Satya<br/>+ Aggravated Assault",
             "combat untaps all lands → infinite combats → infinite tokens + ETBs", "decap T6–7", "combo"),
            ("brudiclad", "Brudiclad + a token pile<br/>+ a fat Satya copy (Inferno Titan)",
             "convert every token into the bomb → lethal alpha (no infinite needed)", "decap T7", "combat"),
            ("adeline", "Adeline + Anointed Procession",
             "~6 humans per attack + doubled Satya token → wide alpha swing", "decap T7–8", "combat"),
            ("conscripts", "Satya copies Zealous Conscripts<br/>(+ Strionic Resonator / Aggravated Assault)",
             "steal the pod's best permanents, one per combat", "disrupt → decap", "enabler"),
            ("grind", "repeated ETB copies (Inferno Titan ping,<br/>Cloudblazer draw, Skyclave exile) (fallback)",
             "grind the pod out over 3–4 combats", "table T10+", "table"),
        ],
        "stall": "Satya must survive as a 3/5 through combat — protect her<br/>(Greaves / Boots / Slip Out the Back) and hold for a safe swing",
        "src": "rc_speed_lab.py + The_Replication_Crisis_Summary.md",
    },
}


# --------------------------------------------------------------------------- helpers
def resolve_deck(stem):
    """Newest decks/{stem}-*.txt (the dated filename is the version history), or None."""
    hits = sorted(DECK_DIR.glob(f"{stem}-*.txt"))
    return hits[-1] if hits else None


def fb_decks():
    """framework_bakeoff.DECKS shape: slug -> (name, stem, cc, cc_axes). Order preserved."""
    return {s: (d["name"], d["stem"], d["cc"], d["cc_axes"]) for s, d in DECKS.items()}


def win_lines():
    """framework_bakeoff.WIN_LINE shape: slug -> win_line dict."""
    return {s: d["win_line"] for s, d in DECKS.items()}


def judgment():
    """keep_spec.JUDGMENT shape: slug -> (bottleneck, min_lands, max_lands, hi_curve, mixed)."""
    return {s: (d["bottleneck"], d["min_lands"], d["max_lands"], d["hi_curve"], d["mixed"])
            for s, d in DECKS.items()}


def also():
    """keep_spec.ALSO shape: slug -> [secondary axes] — only the two-line decks (those with `also`)."""
    return {s: d["also"] for s, d in DECKS.items() if d.get("also")}


def active_commanders():
    """deck_sim COMMANDERS contribution: stem -> commander, for the active roster."""
    return {d["stem"]: d["commander"] for d in DECKS.values()}


def active_display():
    """deck_sim DISPLAY contribution: stem -> display name, for the active roster."""
    return {d["stem"]: d["name"] for d in DECKS.values()}


def kill_trees():
    """kill_tree.DECKS shape: display-slug -> spec (title/root/background/lines/stall/src),
    in render order. The `reg_slug` cross-reference is dropped (kill_tree doesn't use it)."""
    return {slug: {k: v for k, v in spec.items() if k != "reg_slug"}
            for slug, spec in KILL_TREES.items()}


def deck_key_index():
    """deck_key (== stem) -> slug, for harvesters that key by the decklist stem."""
    return {d["stem"]: s for s, d in DECKS.items()}
