#!/usr/bin/env python3
"""mulligan_trainer.py — a keep/mulligan DRILL for the roster (Backlog #5 spin-off).

While Layer C (real games, Backlog #10) is blocked on actually playing, the one thing
that turns "waiting for games" into "getting better at the games I'll log" is rep on the
single most frequent decision in a game: keep this opening hand, or mulligan?

This deals you raw 7-card hands from a chosen deck (NO auto-mulligan — you call it), then
reveals what the deck's PLAN-AWARE keep model would do and WHY, and scores how often you
agree with it across the session.

WHAT THE "ANSWER" IS — AND ISN'T. The verdict comes straight from `deck_sim.keep_hand`
with the deck's keep-spec installed (analysis/keep_specs.json, generated by keep_spec.py
from the verified WIN_LINE + tagger; the JUDGMENT layer was hand-curated with the user
2026-06-16). So it is the SAME heuristic the sim mulligans on — not a rules-engine oracle,
not "ground truth." It is a documented model of "does this hand advance THIS deck's plan"
(FINDING a piece / MANA acceleration / BOARD-commander-on-curve). Treat disagreements as a
prompt to think, not as you being wrong — keepable% is a deckbuilding INPUT, not a verdict
([[feedback_mulligan_is_deckbuilding_input]]). The model also can't see the things a real
keep weighs: colours in the band, the specific pod, on-the-play vs draw. It drills the
PLAN-PROGRESS axis the sim encodes; you supply the rest.

Caveat inherited from the sim: the London mulligan here is to a flat 7 (no bottoming
modelled), so this drills the keep/ship DECISION on the opening 7, not the bottom-N craft.

Run (interactive, for a human terminal):
    python scripts/mulligan_trainer.py --deck genome          # 10 hands, you call each
    python scripts/mulligan_trainer.py --deck rad --rounds 20 --seed 7
    python scripts/mulligan_trainer.py --list                 # decks with a keep-spec

Run (non-interactive, for demo / CI / me):
    python scripts/mulligan_trainer.py --deck genome --auto --rounds 5 --seed 1
"""
import argparse
import importlib.util
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        try:
            _s.reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):
            pass


def _imp(name):
    spec = importlib.util.spec_from_file_location(name, Path(__file__).parent / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


ds = _imp("deck_sim")
deck_registry = ds.deck_registry

AXIS_GLOSS = {
    "FINDING": "keep a key piece / tutor / 2+ selection cards",
    "MANA": "keep ramp (or a high-curve land hand)",
    "BOARD": "deploy the commander ~on curve + have an early (cmc≤3) play",
}
BUCKETS = ("key_cards", "tutors", "ramp", "selection")
BUCKET_LABEL = {"key_cards": "KEY", "tutors": "TUTOR", "ramp": "RAMP", "selection": "DIG"}


# --------------------------------------------------------------------------- deck resolve
def resolve_spec(frag):
    """Fuzzy-match a deck fragment to its keep-spec (keyed by deck_key/stem)."""
    specs = ds._load_keep_specs()
    if not specs:
        sys.exit("no analysis/keep_specs.json — run: python scripts/keep_spec.py --write")
    frag = (frag or "").lower()
    hits = [s for s in specs.values()
            if frag in s["deck_key"].lower() or frag in s["name"].lower()]
    if not frag or len(hits) != 1:
        names = "\n  ".join(f"{s['deck_key']:<26} {s['name']}" for s in specs.values())
        if not frag:
            sys.exit(f"--deck required. Decks with a keep-spec:\n  {names}")
        if not hits:
            sys.exit(f"no deck matches {frag!r}. Decks:\n  {names}")
        joined = ", ".join(h["name"] for h in hits)
        sys.exit(f"{frag!r} is ambiguous ({joined}). Be more specific.")
    return hits[0]


def load_library(spec, index):
    stem = spec["deck_key"]
    path = deck_registry.resolve_deck(stem)
    if path is None:
        sys.exit(f"no decklist found for {stem} (decks/{stem}-*.txt)")
    aliases = ds.load_reskin_aliases()
    library, commander, diag = ds.parse_deck(path, index, aliases)
    if diag["unresolved"]:
        print(f"  (warn: {len(diag['unresolved'])} unresolved card(s) — treated as non-key)",
              file=sys.stderr)
    return library, commander, path


# --------------------------------------------------------------------------- scoring brain
def verdict(hand, spec):
    """The model's keep/mull call + a structured WHY. Reuses deck_sim's installed-spec
    keep_hand (the single source of verdict truth) and its per-axis _axis_ok helper, so the
    drill can NEVER disagree with the sim it's training you against. `spec` must be the
    INSTALLED copy (has `_sets`) — see install()."""
    lands = sum(1 for _, rec in hand if ds.is_land(rec))
    names = {nm.lower() for nm, _ in hand}
    has_ramp = bool(names & spec["_sets"]["ramp"])

    band_ok = spec["min_lands"] <= lands <= spec["max_lands"]
    axes = [spec["bottleneck"], *spec.get("also", [])]
    axes_ok = {ax: ds._axis_ok(ax, hand, lands, spec, names, has_ramp) for ax in axes}
    keep = ds.keep_hand(hand)              # == band_ok and any(axes_ok) — the authority

    reasons = []
    reasons.append(f"lands {lands} vs band {spec['min_lands']}-{spec['max_lands']} "
                   f"→ {'ok' if band_ok else 'OUT OF BAND'}")
    if not band_ok:
        reasons.append("band fails → ship regardless of plan")
    else:
        for ax in axes:
            tag = "satisfied" if axes_ok[ax] else "no"
            reasons.append(f"{ax} ({AXIS_GLOSS[ax]}): {tag}")
        if not any(axes_ok.values()):
            reasons.append("no plan axis advanced → ship")
    return keep, reasons


def card_tags(name, rec, spec):
    """Display tags for one card: LAND + any keep-spec buckets it belongs to."""
    tags = []
    if ds.is_land(rec):
        tags.append("LAND")
    low = name.lower()
    for b in BUCKETS:
        if low in spec["_sets"][b]:
            tags.append(BUCKET_LABEL[b])
    return tags


def show_hand(hand, spec):
    for nm, rec in sorted(hand, key=lambda h: (not ds.is_land(h[1]), h[1]["cmc"], h[0])):
        cmc = "" if ds.is_land(rec) else f"{rec['cmc']:.0f}"
        tags = card_tags(nm, rec, spec)
        tagstr = f"  [{' '.join(tags)}]" if tags else ""
        type_short = rec["type_line"].split("—")[0].strip()
        print(f"    {cmc:>2}  {nm:<32} {type_short:<22}{tagstr}")


# --------------------------------------------------------------------------- session
def deal(library, rng):
    deck = list(library)
    rng.shuffle(deck)
    return deck[:7]


def install(spec):
    """Install the spec into deck_sim and return the INSTALLED copy (carries `_sets`),
    which keep_hand/_axis_ok consult and which card_tags/verdict read."""
    ds.set_keep_spec(spec)
    return ds._KEEP_SPEC


def play(spec, library, commander, rounds, rng, auto):
    spec = install(spec)
    print(f"\n=== Mulligan drill — {spec['name']} ===")
    axes = " + ".join([spec["bottleneck"], *spec.get("also", [])])
    print(f"commander: {commander}  ·  plan axis: {axes}  ·  land band "
          f"{spec['min_lands']}-{spec['max_lands']}")
    if spec.get("mixed"):
        print(f"note: {spec['mixed']}")
    print("Call KEEP or MULL on the opening 7. The model's call (deck_sim plan-keep) is a "
          "heuristic, not an oracle — disagreements are a prompt to think.\n")

    agree = seen = 0
    over_keep = over_mull = 0
    for i in range(1, rounds + 1):
        hand = deal(library, rng)
        print(f"--- Hand {i}/{rounds} ---")
        show_hand(hand, spec)
        model_keep, reasons = verdict(hand, spec)

        if auto:
            user_keep = None
        else:
            try:
                ans = input("    keep / mull?  [k/m] (q to quit) > ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print("\n(quitting)")
                break
            if ans in ("q", "quit"):
                break
            user_keep = ans in ("k", "keep", "y", "yes")

        verb = "KEEP" if model_keep else "MULL"
        print(f"    model says: {verb}")
        for r in reasons:
            print(f"      - {r}")
        if user_keep is not None:
            seen += 1
            if user_keep == model_keep:
                agree += 1
                print("    ✓ you agreed")
            else:
                print(f"    ✗ you said {'KEEP' if user_keep else 'MULL'}")
                if user_keep and not model_keep:
                    over_keep += 1
                else:
                    over_mull += 1
        print()

    if seen:
        pct = 100 * agree / seen
        print(f"=== {agree}/{seen} agreed with the model ({pct:.0f}%) ===")
        if over_keep > over_mull and over_keep:
            print(f"  You over-KEPT {over_keep}× — the model shipped hands you held. Watch for "
                  f"band-passing hands that don't actually advance the {spec['bottleneck']} plan.")
        elif over_mull > over_keep and over_mull:
            print(f"  You over-MULLED {over_mull}× — the model kept hands you shipped. The plan "
                  f"axis was satisfied; you may be too strict.")
        elif agree == seen:
            print("  Perfect agreement with the plan-keep model this session.")
    elif auto:
        print(f"=== auto: dealt {rounds} hand(s), no scoring ===")


# --------------------------------------------------------------------------- bake (dashboard)
def _card_record(name, rec, spec):
    """Serializable card for a baked hand: name, cmc (None for lands), land flag, tags."""
    land = ds.is_land(rec)
    return {"n": name, "cmc": None if land else int(rec["cmc"]),
            "land": land, "tags": card_tags(name, rec, spec)}


def bake_hands(slug, n=40, seed=0):
    """A static, no-backend mulligan-drill payload for the dashboard: N opening hands from
    `slug`'s current decklist, each carrying the AUTHORITATIVE keep_hand verdict + the same
    human reasons the CLI prints. The verdicts are computed HERE (the Python authority) and
    baked, so the client renders them without re-implementing keep_hand — no drift, exactly
    the property the trainer guarantees. Returns None when the deck has no keep-spec or the
    Scryfall bulk is absent (the dashboard then hides the drill)."""
    reg = ds.deck_registry.DECKS.get(slug)
    if reg is None:
        return None
    spec = ds._load_keep_specs().get(reg["stem"])
    if spec is None or not ds.ORACLE.exists():
        return None
    library, commander, _ = load_library(spec, ds.load_oracle_index())
    spec = install(spec)
    rng = random.Random(seed)
    hands = []
    for _ in range(n):
        hand = deal(library, rng)
        keep, reasons = verdict(hand, spec)
        cards = sorted((_card_record(nm, rec, spec) for nm, rec in hand),
                       key=lambda c: (not c["land"], c["cmc"] if c["cmc"] is not None else -1, c["n"]))
        hands.append({"cards": cards, "lands": sum(c["land"] for c in cards),
                      "keep": keep, "reasons": reasons})
    axes = [spec["bottleneck"], *spec.get("also", [])]
    return {"deckKey": reg["stem"], "commander": commander,
            "bottleneck": spec["bottleneck"], "also": spec.get("also", []),
            "minLands": spec["min_lands"], "maxLands": spec["max_lands"],
            "axisGloss": {ax: AXIS_GLOSS[ax] for ax in axes},
            "mixed": spec.get("mixed"), "hands": hands}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--deck", help="deck fragment (name or stem); fuzzy")
    ap.add_argument("--rounds", type=int, default=10, help="hands to deal (default 10)")
    ap.add_argument("--seed", type=int, default=None, help="rng seed (reproducible drill)")
    ap.add_argument("--auto", action="store_true",
                    help="non-interactive: show each hand + the model's call, no prompt")
    ap.add_argument("--list", action="store_true", help="list decks that have a keep-spec")
    a = ap.parse_args()

    if a.list:
        for s in ds._load_keep_specs().values():
            print(f"  {s['deck_key']:<26} {s['name']}")
        return

    spec = resolve_spec(a.deck)
    index = ds.load_oracle_index()
    library, commander, _ = load_library(spec, index)
    rng = random.Random(a.seed)
    play(spec, library, commander, a.rounds, rng, a.auto)


if __name__ == "__main__":
    main()
